### PR TITLE
Feature: What Is That Error

### PR DESCRIPTION
**Pull request by zardyh**
- [ ] `parser/0002.txt` ---  Parser:     UnexpectedCharacter
- [ ] `parser/0003.txt` ---  Parser:     UnexpectedEnd
- [x] `parser/0004.txt` ---  Parser:     UnclosedString
- [x] `parser/0005.txt` ---  Parser:     UnclosedComment
- [ ] `parser/0006.txt` ---  Parser:     UnexpectedToken
- [ ] `parser/0007.txt` ---  Parser:     MalformedClass
- [ ] `parser/0008.txt` ---  Parser:     MalformedInstance
- [x] `parser/0009.txt` ---  Parser:     MisplacedWith
- [x] `parser/0010.txt` ---  Parser:     BindQualified
- [x] `parser/0011.txt` ---  Parser:     InvalidEscapeCode
- [x] `parser/0012.txt` ---  Parser:     UnalignedIn
- [x] `resolve/1001.txt` --- Resolver:   NotInScope
- [x] `resolve/1002.txt` --- Resolver:   Ambiguous
- [x] `resolve/1003.txt` --- Resolver:   NonLinearPattern
- [x] `resolve/1004.txt` --- Resolver:   NonLinearRecord
- [ ] `resolve/1006.txt` --- Resolver:   EmptyBegin
- [x] `resolve/1007.txt` --- Resolver:   IllegalMethod
- [ ] `resolve/1008.txt` --- Resolver:   LastStmtNotExpr
- [x] `resolve/1009.txt` --- Resolver:   LetOpenStruct
- [x] `resolve/1010.txt` --- Resolver:   UnresolvedImport
- [x] `resolve/1011.txt` --- Resolver:   ImportLoop
- [ ] `resolve/1012.txt` --- Resolver:   TFClauseWrongHead
- [ ] `resolve/1013.txt` --- Resolver:   TFClauseWrongArity
- [x] `types/2001.txt` ---   TC:         NotEqual
- [x] `types/2002.txt` ---   TC:         Occurs
- [x] `types/2003.txt` ---   TC:         CustomTypeError
- [x] `types/2004.txt` ---   TC:         NotInScope
- [x] `types/2005.txt` ---   TC:         FoundHole
- [ ] `types/2006.txt` ---   TC:         Impredicative
- [ ] `types/2007.txt` ---   TC:         ImpredicativeApp
- [ ] `types/2008.txt` ---   TC:         EscapedSkolems
- [ ] `types/2009.txt` ---   TC:         SkolBinding
- [ ] `types/2010.txt` ---   TC:         NoOverlap
- [ ] `types/2011.txt` ---   TC:         CanNotInstance
- [ ] `types/2012.txt` ---   TC:         Malformed
- [ ] `types/2013.txt` ---   TC:         PatternRecursive
- [ ] `types/2014.txt` ---   TC:         DeadBranch
- [ ] `types/2015.txt` ---   TC:         AmbiguousType
- [ ] `types/2016.txt` ---   TC:         ValueRestriction
- [ ] `types/2017.txt` ---   TC:         AmbiguousMethodTy
- [ ] `types/2018.txt` ---   TC:         UnsatClassCon
- [ ] `types/2019.txt` ---   TC:         ClassStackOverflow
- [ ] `types/2020.txt` ---   TC:         WrongClass
- [ ] `types/2021.txt` ---   TC:         Overlap
- [ ] `types/2022.txt` ---   TC:         UndefinedMethods
- [ ] `types/2023.txt` ---   TC:         UndefinedTyFam
- [ ] `types/2024.txt` ---   TC:         TyFamLackingArgs
- [ ] `types/2025.txt` ---   TC:         MagicInstance
- [ ] `types/2026.txt` ---   TC:         TypeFamInInstHead
- [ ] `types/2027.txt` ---   TC:         InvalidContext
- [ ] `types/2028.txt` ---   TC:         OrphanInstance
- [ ] `types/2029.txt` ---   TC:         NotAClass
- [ ] `types/2030.txt` ---   TC:         CanNotVta
- [ ] `types/2031.txt` ---   TC:         NotPromotable
- [ ] `types/2032.txt` ---   TC:         WildcardNotAllowed
- [x] `types/2033.txt` ---   TC:         NotValue
- [x] `types/2034.txt` ---   TC:         UnsaturatedTS
- [ ] `types/2035.txt` ---   TC:         NotCovered
- [x] `types/2036.txt` ---   TC:         MightNotTerminate
- [x] `types/2037.txt` ---   TC:         TyFunInLhs
- [ ] `verify/3001.txt` ---  Verify:     NonRecursiveRhs
- [ ] `verify/3002.txt` ---  Verify:     DefinedUnused
- [x] `verify/3003.txt` ---  Verify:     ParseErrorInForeign
- [x] `verify/3004.txt` ---  Verify:     LazyLet
- [ ] `verify/3005.txt` ---  Verify:     RedundantArm
- [ ] `verify/3006.txt` ---  Verify:     MissingPattern
- [x] `verify/3007.txt` ---  Verify:     MatchToLet
- [x] `verify/3008.txt` ---  Verify:     MatchToFun
- [ ] `verify/3009.txt` ---  Verify:     ToplevelRefBinding

### CODE REVIEW

**Comment by zardyh** [comment]
@SquidDev `NonRecursiveRhs` is literally as far from a meaningful name as you can get—The error is for _recursive_ rhs's!

**Comment by SquidDev** [comment]
Just keeping track of current progress as a shell script:

```
$ find doc/errors/ -type f -size -50c | sort
doc/errors/parser/0002.txt
doc/errors/parser/0003.txt
doc/errors/parser/0006.txt
doc/errors/parser/0007.txt
doc/errors/parser/0008.txt
doc/errors/resolve/1008.txt
doc/errors/resolve/1012.txt
doc/errors/resolve/1013.txt
doc/errors/types/2006.txt
doc/errors/types/2008.txt
doc/errors/types/2009.txt
doc/errors/types/2010.txt
doc/errors/types/2011.txt
doc/errors/types/2012.txt
doc/errors/types/2013.txt
doc/errors/types/2014.txt
doc/errors/types/2015.txt
doc/errors/types/2017.txt
doc/errors/types/2018.txt
doc/errors/types/2019.txt
doc/errors/types/2020.txt
doc/errors/types/2021.txt
doc/errors/types/2022.txt
doc/errors/types/2023.txt
doc/errors/types/2024.txt
doc/errors/types/2025.txt
doc/errors/types/2026.txt
doc/errors/types/2027.txt
doc/errors/types/2028.txt
doc/errors/types/2029.txt
doc/errors/types/2030.txt
doc/errors/types/2031.txt
doc/errors/types/2032.txt
doc/errors/types/2035.txt
doc/errors/types/2038.txt
doc/errors/types/2039.txt
doc/errors/verify/3001.txt
doc/errors/verify/3002.txt
doc/errors/verify/3003.txt
doc/errors/verify/3004.txt
doc/errors/verify/3005.txt
doc/errors/verify/3006.txt
doc/errors/verify/3007.txt
doc/errors/verify/3008.txt
doc/errors/verify/3009.txt
```

**Comment by zardyh** [comment]
Here's what we're missing:
```
% find doc/errors/ -type f -size -50c | sort
doc/errors/parser/0002.txt
doc/errors/parser/0003.txt
doc/errors/parser/0006.txt
doc/errors/parser/0007.txt
doc/errors/parser/0008.txt
doc/errors/resolve/1008.txt
doc/errors/resolve/1012.txt
doc/errors/resolve/1013.txt
doc/errors/types/2008.txt
doc/errors/types/2013.txt
doc/errors/types/2028.txt
doc/errors/types/2029.txt
doc/errors/types/2030.txt
doc/errors/types/2031.txt
doc/errors/types/2032.txt
doc/errors/types/2035.txt
doc/errors/types/2038.txt
doc/errors/types/2039.txt
doc/errors/verify/3001.txt
doc/errors/verify/3002.txt
doc/errors/verify/3005.txt
doc/errors/verify/3006.txt
doc/errors/verify/3009.txt
```

**Comment by zardyh** [comment]
I finished resolve and did one in verify:

```
doc/errors/parser/0002.txt
doc/errors/parser/0003.txt
doc/errors/parser/0006.txt
doc/errors/parser/0007.txt
doc/errors/parser/0008.txt
doc/errors/types/2008.txt
doc/errors/types/2013.txt
doc/errors/types/2028.txt
doc/errors/types/2029.txt
doc/errors/types/2030.txt
doc/errors/types/2031.txt
doc/errors/types/2032.txt
doc/errors/types/2035.txt
doc/errors/types/2038.txt
doc/errors/types/2039.txt
doc/errors/verify/3001.txt
doc/errors/verify/3002.txt
doc/errors/verify/3005.txt
doc/errors/verify/3006.txt
```

**Pull request merged**
